# Generated by Django 4.1.1 on 2022-10-17 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_remove_favorites_des_remove_favorites_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
        migrations.AddField(
            model_name='favorite',
            name='favbooks',
            field=models.ManyToManyField(to='main_app.book'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
